export const REORDER_TIMESTAMPS = "REORDER_TIMESTAMPS"
export const ADD_TIMESTAMP      = "ADD_TIMESTAMP"
export const CHANGE_FOLDER_ID   = "CHANGE_FOLDER_ID"
export const LOAD_VIDEOS        = "LOAD_VIDEOS"